### ISSUE TITLE
Where could I download the Mesh refinement network pre trained model?

### ISSUE THREAD

**Issue by wangyujiewj** [tangjiapeng/SkeletonBridgeRecon#2]
I am interested in this paper, and I want to run the demo_deform.py.

**Comment by tangjiapeng** [comment]
I don't provide the mesh refinement model  because I change some settings on the base mesh generation and simplication in the released code. And I have no time to retrain this stage.  If you want  the pretrained model  of stage 3 now, you can seed email to me.  I can provide a pretrained model trained on the old settings.
